---
# tasks file for inno_launch_container
- name: Selection du task file en fonction de la version d'ansible
  set_fact:
    docker_tasks_file: >-
      {% if ansible_version.full is version('2.10', '>=') %}task_after_2.10.yml{% else %}task_before_2.10.yml{% endif %}

- name: Lancement du task file
  ansible.builtin.include_tasks: 
    file: "{{ docker_tasks_file }}"



   

