 ## -- Playbook par QBABULEAUD
  
- name: Installation initial de prestashop  ## Lancement de l'installation de docker et de ses dépendances
  remote_user: "{{ my_remote_user }}" # Utilisateur qui initiera le cmd distantes
  become: true # Permet d'initié les commandes en temps que sudoers
  hosts: FAJITAS # Machine ciblé par les tasks
  gather_facts: no
  vars_files : # Variables utilisé dans les tasks qui suivent
    - vars/main.yml
    - vars/olow.yml
  tasks:

#### == Création de l'environnement du site et déploiement de celui ci == ####
  # - name: Installation de docker et de ses prérequis
  #   include_role:
  #       name: inno_docker

  - name: Creation du dossier du projet
    file:
      path: "{{ user_home }}/{{ project_name }}/vhost/"  
      state: directory
      recurse: yes
      owner: "{{ my_remote_user }}"
      group: www-data
      mode: 0755

  - name: Generation du Vhost
    template:
      src: "templates/vhost.conf.j2"
      dest: "{{ user_home }}/{{ project_name }}/vhost/{{ project_name }}.conf"
      owner: root
      group: www-data
      mode: 0755

  - name: Lancement des containers
    include_role:
        name: inno_launch_containers

## Activation du site
  - name: Activation Site
    shell: docker exec Inno_{{ project_name }}_{{ docker_container[1].name }} a2ensite {{ project_name }}.conf

## Desactivation du vhost par défaut
  - name: Désactivation du vhost par defaut
    shell: docker exec Inno_{{ project_name }}_{{ docker_container[1].name }} a2dissite 000-default.conf

# Preparation du déplacement du dossier html
  - name: Copie du script
    template:
      src: ./templates/move_app.sh.j2
      dest: "{{ user_home }}/{{ project_name }}/move_app.sh"
      owner: "{{ my_remote_user }}"
      group: "{{ my_remote_user }}"
      mode: '0755'

  - name: Copie du script
    template:
      src: ./templates/install_finalisation.sh.j2
      dest: "{{ user_home }}/{{ project_name }}/install_finalisation.sh"
      owner: "{{ my_remote_user }}"
      group: "{{ my_remote_user }}"
      mode: '0755'

  - name: Copie du script dans le container
    shell: docker cp "{{ user_home }}/{{ project_name }}/move_app.sh"  Inno_{{ project_name }}_{{ docker_container[1].name }}:/tmp/move_app.sh


  - name: Lancement du script
    shell: docker exec Inno_{{ project_name }}_{{ docker_container[1].name }} /tmp/move_app.sh

## reload apache 
  - name: Reload apache
    shell: docker exec Inno_{{ project_name }}_{{ docker_container[1].name }} service apache2 start

 




